### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by maoudia-via** [ingonyama-zk/poseidon-hash#9]
Currently installing the library with python 3.11 leads to the following error from numba:
RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.

Also it seems numba now supports python 3.11: https://github.com/numba/numba/issues/8304

**Comment by omershlo** [comment]
thanks @maoudia-via ! 
we will fix, 

cc: @LeonHibnik

**Comment by mbronckers** [comment]
Just bumping this as it is still not fixed.

**Comment by omershlo** [comment]
Thanks! 
@seemenkina will resolve but cannot commit to a timeline.. feel free to fix and push

**Comment by seemenkina** [comment]
@maoudia-via @mbronckers sorry for the wait, I updated the code and package on pypi

**Comment by maoudia-via** [comment]
Thank you so much @seemenkina  !
